# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.7.1-node-browsers

    working_directory: ~/repo

    branches:
      only:
        - master

    steps:
      - add_ssh_keys:
          fingerprints:
            - "bb:37:1e:f6:bf:64:3d:f9:5a:8e:82:c1:a6:a9:e4:a9"

      - checkout

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: Set bundle installation path
          command: bundle config set path 'vendor/bundle'

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "documentation/Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: install documentation dependencies
          command: cd documentation && bundle install --jobs=4 --retry=3 --path vendor/bundle && cd -

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "documentation/Gemfile.lock" }}

      - run:
          name: Run tests
          command: bundle exec rspec --format progress

      - run:
          name: Deploy documentation
          command: cd documentation && ./deploy.sh
