# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bb:37:1e:f6:bf:64:3d:f9:5a:8e:82:c1:a6:a9:e4:a9"
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    branches:
      only:
        - master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "documentation/Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: install documentation dependencies
          command: cd documentation && bundle install --jobs=4 --retry=3 --path vendor/bundle && cd -

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "documentation/Gemfile.lock" }}

      - run:
          name: Run tests
          command: bundle exec rspec --format progress

      - run:
          name: Deploy documentation
          command: cd documentation && ./deploy.sh
